export const LOADER = 'LOADER';

export const SHOW_TOAST = 'SHOW_TOAST';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_RESPONSE = 'SIGNUP_RESPONSE';

export const OTP_REQUEST = 'OTP_REQUEST';
export const OTP_RESPONSE = 'OTP_RESPONSE';

export const VERIFY_OTP_REQUEST = 'VERIFY_OTP_REQUEST';
export const VERIFY_OTP_RESPONSE = 'VERIFY_OTP_RESPONSE';

export const FORGOT_OTP_REQUEST = 'FORGOT_OTP_REQUEST';
export const FORGOT_OTP_RESPONSE = 'FORGOT_OTP_RESPONSE';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_RESPONSE = 'CHANGE_PASSWORD_RESPONSE';

export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_RESPONSE = 'PROFILE_RESPONSE';

export const PROFILE_CATEGORY_REQUEST = 'PROFILE_CATEGORY_REQUEST';
export const PROFILE_CATEGORY_RESPONSE = 'PROFILE_CATEGORY_RESPONSE';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_RESPONSE = 'UPDATE_PROFILE_RESPONSE';

export const RECOMMENDEDJOBS_REQUEST = 'RECOMMENDEDJOBS_REQUEST';
export const RECOMMENDEDJOBS_RESPONSE = 'RECOMMENDEDJOBS_RESPONSE';

export const APPLIEDJOBS_REQUEST = 'APPLIEDJOBS_REQUEST';
export const APPLIEDJOBS_RESPONSE = 'APPLIEDJOBS_RESPONSE';

export const APPLY_NOW_REQUEST = 'APPLY_NOW_REQUEST';
export const APPLY_NOW_RESPONSE = 'APPLY_NOW_RESPONSE';

export const LOCATION_REQUEST = 'LOCATION_REQUEST';
export const LOCATION_RESPONSE = 'LOCATION_RESPONSE';

export const CONTACT_SUPPORT_REQUEST = 'CONTACT_SUPPORT_REQUEST';
export const CONTACT_SUPPORT_RESPONSE = 'CONTACT_SUPPORT_RESPONSE';

export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_RESPONSE = 'SEARCH_RESPONSE';

export const IGNORE_JOBS_REQUEST = 'IGNORE_JOBS_REQUEST';
export const IGNORE_JOBS_RESPONSE = 'IGNORE_JOBS_RESPONSE';

export const ONGOING_JOBS_REQUEST = 'ONGOING_JOBS_REQUEST';
export const ONGOING_JOBS_RESPONSE = 'ONGOING_JOBS_RESPONSE';

export const HIRE_REQUESTS_REQUEST = 'HIRE_REQUESTS_REQUEST';
export const HIRE_REQUESTS_RESPONSE = 'HIRE_REQUESTS_RESPONSE';

export const MY_SUBSCRITPTION_REQUEST = 'MY_SUBSCRITPTION_REQUEST';
export const MY_SUBSCRITPTION_RESPONSE = 'MY_SUBSCRITPTION_RESPONSE';

export const SUBSCRITPTION_PLAN_REQUEST = 'SUBSCRITPTION_PLAN_REQUEST';
export const SUBSCRITPTION_PLAN_RESPONSE = 'SUBSCRITPTION_PLAN_RESPONSE';

export const JOBS_NEAR_ME_REQUEST = 'JOBS_NEAR_ME_REQUEST';
export const JOBS_NEAR_ME_RESPONSE = 'JOBS_NEAR_ME_RESPONSE';

export const JOBS_NEAR_MEWC_REQUEST = 'JOBS_NEAR_MEWC_REQUEST';
export const JOBS_NEAR_MEWC_RESPONSE = 'JOBS_NEAR_MEWC_RESPONSE';

export const ACCEPT_HIRE_REQUESTS_REQUEST = 'ACCEPT_HIRE_REQUESTS_REQUEST';
export const ACCEPT_HIRE_REQUESTS_RESPONSE = 'ACCEPT_HIRE_REQUESTS_RESPONSE';

export const MESSAGE_LIST_REQUEST = 'MESSAGE_LIST_REQUEST';
export const MESSAGE_LIST_RESPONSE = 'MESSAGE_LIST_RESPONSE';

export const CREATE_PLAY_LIST_REQUEST = 'CREATE_PLAY_LIST_REQUEST';
export const CREATE_PLAY_LIST_RESPONSE = 'CREATE_PLAY_LIST_RESPONSE';

export const GET_CREATE_PLAY_LIST_REQUEST = 'GET_CREATE_PLAY_LIST_REQUEST';
export const GET_CREATE_PLAY_LIST_RESPONSE = 'GET_CREATE_PLAY_LIST_RESPONSE';

export const ADD_LIST_REQUEST = 'ADD_LIST_REQUEST';
export const ADD_LIST_RESPONSE = 'ADD_LIST_RESPONSE';

export const PLAY_LIST_REQUEST = 'PLAY_LIST_REQUEST';
export const PLAY_LIST_RESPONSE = 'PLAY_LIST_RESPONSE';

export const DELETE_PLAY_LIST_REQUEST = 'DELETE_PLAY_LIST_REQUEST';
export const DELETE_PLAY_LIST_RESPONSE = 'DELETE_PLAY_LIST_RESPONSE';

export const UPDATE_TIME_SHEET_REQUEST = 'UPDATE_TIME_SHEET_REQUEST';
export const UPDATE_TIME_SHEET_RESPONSE = 'UPDATE_TIME_SHEET_RESPONSE';

export const CREATE_TIME_SHEET_REQUEST = 'CREATE_TIME_SHEET_REQUEST';
export const CREATE_TIME_SHEET_RESPONSE = 'CREATE_TIME_SHEET_RESPONSE';

export const UNLOCKED_BY_REQUEST = 'UNLOCKED_BY_REQUEST';
export const UNLOCKED_BY_RESPONSE = 'UNLOCKED_BY_RESPONSE';

export const CREATE_END_JOB_REQUEST = 'CREATE_END_JOB_REQUEST';
export const CREATE_END_JOB_RESPONSE = 'CREATE_END_JOB_RESPONSE';

export const AVAILABILITY_PT_REQUEST = 'AVAILABILITY_PT_REQUEST';
export const AVAILABILITY_PT_RESPONSE = 'AVAILABILITY_PT_RESPONSE';

export const GET_AVAILABILITY_PT_REQUEST = 'GET_AVAILABILITY_PT_REQUEST';
export const GET_AVAILABILITY_PT_RESPONSE = 'GET_AVAILABILITY_PT_RESPONSE';

export const SKILLS_REQUEST = 'SKILLS_REQUEST';
export const SKILLS_RESPONSE = 'SKILLS_RESPONSE';

export const TIME_SHEET_REQUEST = 'TIME_SHEET_REQUEST';
export const TIME_SHEET_RESPONSE = 'TIME_SHEET_RESPONSE';

export const JOB_SKILLS_REQUEST = 'JOB_SKILLS_REQUEST';
export const JOB_SKILLS_RESPONSE = 'JOB_SKILLS_RESPONSE';

export const JOB_EDUCATION_REQUEST = 'JOB_EDUCATION_REQUEST';
export const JOB_EDUCATION_RESPONSE = 'JOB_EDUCATION_RESPONSE';

export const JOB_EXPERIENCE_REQUEST = 'JOB_EXPERIENCE_REQUEST';
export const JOB_EXPERIENCE_RESPONSE = 'JOB_EXPERIENCE_RESPONSE';

export const JOB_CATEGORY_REQUEST = 'JOB_CATEGORY_REQUEST';
export const JOB_CATEGORY_RESPONSE = 'JOB_CATEGORY_RESPONSE';

export const VACANCY_DETAILS_REQUEST = 'VACANCY_DETAILS_REQUEST';
export const VACANCY_DETAILS_RESPONSE = 'VACANCY_DETAILS_RESPONSE';

export const ADD_MESSAGE_LIST_REQUEST = 'ADD_MESSAGE_LIST_REQUEST';
export const ADD_MESSAGE_LIST_RESPONSE = 'ADD_MESSAGE_LIST_RESPONSE';

// * * * * * * * LANGUAGE PART * * * * * * *

export const SET_LANGUAGE = 'SET_LANGUAGE';

